/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package btconfig;

/**
 *
 * @author radioactive
 */
public class fw_update_speed extends javax.swing.JDialog {

  BTFrame parent;

    /**
     * Creates new form fw_update_speed
     */
    public fw_update_speed(BTFrame parent) {
        initComponents();
        setModal(true);
        this.parent = parent;
    }


    public void init() {
      if( parent.usb_slow.isSelected() ) slow.setSelected(true);
      else if( parent.usb_med.isSelected() ) med.setSelected(true);
      else if( parent.usb_fast.isSelected() ) fast.setSelected(true);
          try {
            if( parent.usb_slow.isSelected() ) parent.prefs.put("usb_speed", "slow");
            if( parent.usb_med.isSelected() ) parent.prefs.put("usb_speed", "med");
            if( parent.usb_fast.isSelected() ) parent.prefs.put("usb_speed", "fast");
          } catch(Exception e) {
            e.printStackTrace();
          }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        slow = new javax.swing.JRadioButton();
        med = new javax.swing.JRadioButton();
        fast = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        exit = new javax.swing.JButton();
        ok = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();

        setTitle("FW Update");
        setAlwaysOnTop(true);

        jPanel1.setLayout(new java.awt.GridLayout(2, 1));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("USB Interface Speed"));

        buttonGroup1.add(slow);
        slow.setSelected(true);
        slow.setText("Slow");
        slow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slowActionPerformed(evt);
            }
        });
        jPanel5.add(slow);

        buttonGroup1.add(med);
        med.setText("Med");
        med.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medActionPerformed(evt);
            }
        });
        jPanel5.add(med);

        buttonGroup1.add(fast);
        fast.setText("Fast");
        fast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fastActionPerformed(evt);
            }
        });
        jPanel5.add(fast);

        jPanel1.add(jPanel5);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel4.add(exit);

        ok.setText("OK");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });
        jPanel4.add(ok);

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("New firmware is available. Continue WIth Update?");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void medActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medActionPerformed
      parent.usb_med.setSelected(true);
    }//GEN-LAST:event_medActionPerformed

    private void slowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slowActionPerformed
      parent.usb_slow.setSelected(true);
    }//GEN-LAST:event_slowActionPerformed

    private void fastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fastActionPerformed
      parent.usb_fast.setSelected(true);
    }//GEN-LAST:event_fastActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
      System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
      init();
      setVisible(false);
    }//GEN-LAST:event_okActionPerformed

  /*
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fw_update_speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fw_update_speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fw_update_speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fw_update_speed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fw_update_speed().setVisible(true);
            }
        });
    }
 */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton exit;
    private javax.swing.JRadioButton fast;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton med;
    private javax.swing.JButton ok;
    private javax.swing.JRadioButton slow;
    // End of variables declaration//GEN-END:variables
}
